import React from "react"
import { LayoutNavBar } from "../NavBar"
import Head from "next/head"
const MainLayout = ({ children }: any) => {
    return (
        <div>
            <LayoutNavBar />
            <Head>
                <title>Aimy site</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main style={{ height: "100vh", padding: "35px" }}>{children}</main>
        </div>
    )
}

export default MainLayout
