import React from "react"
import styles from "./MainLayout.module.css"
import { LayoutNavBar } from "../NavBar"
import Head from "next/head"
const MainLayout = ({ children }: any) => {
    return (
        <div className={styles.main}>
            <LayoutNavBar />
            <Head>
                <title>Aimy site</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>{children}</main>
        </div>
    )
}

export default MainLayout
